-- NeverLand Bug Board — Supabase schema
-- Выполните этот файл в Supabase -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.bugs (
  id uuid primary key default gen_random_uuid(),
  ticket_no bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  fixed_at timestamptz,
  title text not null check (char_length(title) between 3 and 120),
  description text not null check (char_length(description) between 3 and 4000),
  category text not null check (category in ('Minecraft','Launcher','Website','Telegram Bot','Design','Other')),
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')),
  status text not null default 'new' check (status in ('new','confirmed','in_progress','fixed','wontfix')),
  version text check (version is null or char_length(version) <= 80),
  reporter_name text check (reporter_name is null or char_length(reporter_name) <= 60),
  steps text check (steps is null or char_length(steps) <= 4000),
  expected text check (expected is null or char_length(expected) <= 2000),
  actual text check (actual is null or char_length(actual) <= 2000)
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.bugs enable row level security;
alter table public.admins enable row level security;

-- Публично можно читать список багов.
drop policy if exists "public_read_bugs" on public.bugs;
create policy "public_read_bugs" on public.bugs for select to anon, authenticated using (true);

-- Публично можно только создавать НОВЫЙ баг. Статус сразу fixed/in_progress подставить нельзя.
drop policy if exists "public_insert_new_bugs" on public.bugs;
create policy "public_insert_new_bugs" on public.bugs for insert to anon, authenticated
with check (status = 'new' and fixed_at is null);

-- Проверка админа вынесена в SECURITY DEFINER функцию, чтобы RLS admins не зациклился.
create or replace function public.is_bug_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;
revoke all on function public.is_bug_admin() from public;
grant execute on function public.is_bug_admin() to authenticated;

-- Только админ может изменять и удалять баги.
drop policy if exists "admin_update_bugs" on public.bugs;
create policy "admin_update_bugs" on public.bugs for update to authenticated
using (public.is_bug_admin()) with check (public.is_bug_admin());

drop policy if exists "admin_delete_bugs" on public.bugs;
create policy "admin_delete_bugs" on public.bugs for delete to authenticated
using (public.is_bug_admin());

-- Админ может прочитать только собственную запись администратора.
drop policy if exists "admin_read_self" on public.admins;
create policy "admin_read_self" on public.admins for select to authenticated
using (user_id = auth.uid());

-- updated_at обновляется автоматически.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists bugs_set_updated_at on public.bugs;
create trigger bugs_set_updated_at before update on public.bugs
for each row execute function public.set_updated_at();

-- После того как создадите своего пользователя в Supabase Authentication,
-- выполните ОДНУ команду ниже, заменив email:
-- insert into public.admins (user_id)
-- select id from auth.users where email = 'YOUR_ADMIN_EMAIL@example.com'
-- on conflict (user_id) do nothing;
